### ISSUE TITLE
Cannot play audio: 404

### ISSUE THREAD

**Issue by vitaly-zdanevich** [Ajaxy/telegram-tt#44] opened 2021-06-25 16:56 UTC
![2021-06-25-195516_1336x368_scrot](https://user-images.githubusercontent.com/3514015/123459752-60087880-d5ef-11eb-997e-d1a4f263869c.png)

**Comment by Ajaxy** [comment] 2021-06-25 18:19
It says you're out of space. Try to sign in and then sign back it — it will clean up app cache. Also, it's better to use web.telegram.org/z/ rather than webz.telegram.org.

**Comment by vitaly-zdanevich** [comment] 2021-06-25 21:57
I click to https://web.telegram.org/z/ and nothing happens. Firefox, Gentoo Linux, Belarus.

**Comment by Ajaxy** [comment] 2021-06-25 22:26
> I click to https://web.telegram.org/z/ and nothing happens. Firefox, Gentoo Linux, Belarus.

Can you provide a screenshot please?

**Comment by vitaly-zdanevich** [comment] 2021-06-27 13:28
![out](https://user-images.githubusercontent.com/3514015/123546275-96b3cf80-d764-11eb-9b05-3003f0536de3.gif)

**Comment by Ajaxy** [comment] 2021-06-28 13:52
That is super weird. Do you have some specific firewall configuration? Can you access https://web.telegram.org or https://web.telegram.org/k/?

**Comment by vitaly-zdanevich** [comment] 2021-06-28 16:17
This two links has the same effect: cannot open. Also tried with VPN TunnelBear.

I am on Gentoo Linux without firewall.

I have such problem only with this Telegram links.

**Comment by Ajaxy** [comment] 2021-11-05 22:05
Not sure what's the cause, unfortunately. Closing the issue as not specific to Web Z.

**Closed by Ajaxy** 2021-11-05 22:05 UTC
