### ISSUE TITLE
can't run dev on windows 

### ISSUE THREAD

**Issue by liangliangdep** [Ajaxy/telegram-tt#180] opened 2022-10-11 16:12 UTC
hello 
 i can't run this dev on my windows computer, i worked for hours now, the error is below, how to sove it ?  thank you for help!
error detail is :

node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: spawn run ENOENT
    at notFoundError (C:\work\telegram-tt-dev\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\work\telegram-tt-dev\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\work\telegram-tt-dev\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess.cp.emit (C:\work\telegram-tt-dev\node_modules\cross-spawn\lib\enoent.js:30:37)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn run',
  path: 'run',
  spawnargs: [
    'print_version',
    '--silent)',
    'webpack',
    'serve',
    '--mode',
    'development'
  ]
}

![QQ图片20221012001221](https://user-images.githubusercontent.com/40605968/195144585-263bc1c4-e132-4157-bd85-00daa14667bf.png)

**Comment by liangliangdep** [comment] 2022-10-11 16:26
any boy helps ?  thanks

**Comment by Chaoses-Ib** [comment] 2022-10-11 16:39
Duplicate of #109.

**Closed** 2022-10-11 16:52 UTC

**Comment by liangliangdep** [comment] 2022-10-11 16:53
> Duplicate of #109.

thank you a lot, you save me hold day! 非常感谢！
